### ISSUE TITLE
[Feature]: Add button to screenshot filtered messages

### ISSUE THREAD

**Issue by Yay295** [LiveTL/ytcfilter#1]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue for LiveTL.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am not reporting a bug. If I am, I will use the bug report issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Is your feature request related to a problem? Please describe.

The old extension had a button to screenshot the currently filtered messages.

### Describe the solution you'd like

A button to screenshot filtered messages.

### Expected behavior

There will be a button to screenshot filtered messages.

**Comment by KentoNishi** [comment]
Check Save>PNG. That exports as a screenshot.

**Comment by Yay295** [comment]
Thanks. Looks like it's not fully working though; I'll create a new issue.

**Comment by Yay295** [comment]
This might be something to add to the README.
