### ISSUE TITLE
[Bug]: Images on Chome/Firefox extension repositories are old

### ISSUE THREAD

**Issue by Yay295** [LiveTL/ytcfilter#4]
### Checklist

- [X] This is an issue for Hyperchat, not LiveTL. I will go to [the LiveTL repo](https://github.com/LiveTL/LiveTL) to report an issue with LiveTL.
- [X] This issue is not a matter of opinion. If it is, I will use the feature suggestion issue template.
- [X] I have checked for a duplicate or similar issue. I made sure to check closed issues as well.
- [X] I am still able to reproduce the issue after I reinstall the extension.
- [X] I have clear instructions to reproduce the bug, even on another machine.
- [X] I am not suggesting a feature. If I am, I will use the feature suggestion issue template.
- [X] By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/LiveTL/HyperChat/blob/master/CODE_OF_CONDUCT.md)

### Describe the bug

The images on the Chome/Firefox extension repositories are old.

### Steps To Reproduce

Look at the following pages:
https://chrome.google.com/webstore/detail/ytcfilter/mnldnbhgfocmkehnlkeanlhfmopepnko
https://addons.mozilla.org/en-US/firefox/addon/ytcfilter/

### Expected behavior

The images will be for the current version of the extension.

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by KentoNishi** [comment]
![image](https://github.com/LiveTL/ytcfilter/assets/38841491/6117429d-9b33-496d-9c11-b7a86c944147)
